export const quotes = [
  'The only people who never fail are those who never try.',
  'Failure is just another way to learn how to do something right.',
  'I failed my way to success.',
  'Every failure brings with it the seed of an equivalent success.',
  'Only those who dare to fail greatly can ever achieve greatly.',
  'It is hard to fail, but it is worse never to have tried to succeed.',
  'Imagination is more important than knowledge.',
  'Hold fast to dreams, for if dreams die, life is a broken winged bird that cannot fly.',
  'The future belongs to those who believe in the beauty of their dreams.',
  'Go confidently in the direction of your dreams. Live the life you have imagined.',
  'You cannot depend on your eyes when your imagination is out of focus.',
  'Commitment leads to action. Action brings your dream closer.',
  'I never think of the future',
  "Don't waste your life in doubts and fears: Spend yourself on the work before you, well assured that the right performance of this hour's duties will be the best preparation for the hours or ages that follow it.",
  'Do not anticipate trouble or worry about what may never happen. Keep in the sunlight.',
  'Take time to deliberate; but when the time for action arrives, stop thinking and go in.',
  'The mind that is anxious about future events is miserable.',
  'Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influences of each.',
  'The art of leadership is saying no, not yes. It is very easy to say yes.',
  'A leader is a dealer in hope.',
  'While a good leader sustains momentum, a great leader increases it.',
  'A general is just as good or just as bad as the troops under his command make him.',
  'To do great things is difficult; but to command great things is more difficult.',
  'Leadership does not always wear the harness of compromise.',
  'I avoid looking forward or backward, and try to keep looking upward.',
  'The more difficulties one has to encounter, within and without, the more significant and the higher in inspiration his life will be.',
  'Every artist was first an amateur.',
  'I was always looking outside myself for strength and confidence, but it comes from within. It is there all of the time.',
  'We can do anything we want to do if we stick to it long enough.',
  'Our business in life is not to get ahead of others, but to get ahead of ourselves.',
  'Insist on yourself. Never imitate.',
  'Who looks outside, dreams. Who looks inside, awakes.',
  'It is not easy to find happiness in ourselves, and it is not possible to find it elsewhere.',
  'The only journey is the one within.',
  'Follow your honest convictions, and stay strong.',
  'The happiness of your life depends upon the quality of your thoughts; therefore guard accordingly.',
  'Action may not always bring happiness; but there is no happiness without action.',
  'Happiness depends more on the inward disposition of mind than on outward circumstances.',
  'There is no happiness except in the realization that we have accomplished something.',
  'Happiness is not a goal, but a by-product.',
  'Happiness is not a state to arrive at, but a manner of traveling.',
  'Purpose is what gives life a meaning.',
  'The significance of a man is not in what he attains but in what he longs to attain.',
  'In all things that you do, consider the end.',
  'Life can be pulled by goals just as surely as it can be pushed by drives.',
  'The virtue lies in the struggle, not in the prize.',
  'To reach a port, we must sail',
  'Success is the child of audacity.',
  'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.',
  'The secret of success is to know something nobody else knows.',
  'The surest way not to fail is to determine to succeed.',
  'I cannot give you the formula for success, but I can give you the formula for failure',
  'Careful thinking and hard work will solve nearly all your problems. Try and see for yourself.',
  'Years teach us more than books.',
  'The only medicine for suffering, crime, and all the other woes of mankind, is wisdom.',
  'The art of being wise is knowing what to overlook.',
  "The great lesson is that the sacred is in the ordinary, that it is to be found in one's daily life, in one's neighbors, friends and family, in one's backyard.",
  'A wise man learns by the mistakes of others, a fool by his own.',
  'No man was ever wise by chance.',
  'In everything the ends well defined are the secret of durable success.',
  'Arriving at one goal is the starting point to another.',
  'A goal is a dream with a deadline.',
  "Most 'impossible' goals can be met simply by breaking them down into bite-size chunks, writing them down, believing them, and then going full speed ahead as if they were routine.",
  'Goals are the fuel in the furnace of achievement.',
  'We are what we repeatedly do. Excellence, therefore, is not an act but a habit.',
  "Take risks and you'll get the payoffs. Learn from your mistakes until you succeed. It's that simple.",
  'The best way out is always through.',
  "You miss 100 percent of the shots you don't take.",
  'Nothing will ever be attempted if all possible objections must first be overcome.',
  "Don't bunt. Aim out of the ballpark.",
  'The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer, not a dreamer.',
  'Never, never, never, never, in nothing great or small, large or petty, never give in except to convictions of honour and good sense. Never yield to force; never yield to the apparently overwhelming might of the enemy.',
  'Your most unhappy customers are your greatest source of learning.',
  'I have not failed. I’ve just found 10,000 ways that won’t work.',
  'Entrepreneurship is neither a science nor an art. It is a practice.',
  'In the modern world of business, it is useless to be a creative, original thinker unless you can also sell what you create.',
  'Success is how high you bounce after you hit bottom.',
  'If you’re not embarrassed by the first version of your product, you’ve launched too late.',
  'Positive thinking will let you do everything better than negative thinking will.',
  'I’m not afraid of dying, I’m afraid of not trying.',
  'Whatever the mind can conceive and believe, the mind can achieve.',
  'The longer you’re not taking action the more money you’re losing',
  'Go Big, or Go Home',
  'Most great people have attained their greatest success just one step beyond their greatest failure',
  'Opportunity is missed by most people because it is dressed in overalls and looks like work',
  'Have the end in mind and every day make sure your working towards it',
  'He who begins many things finishes but few',
  'The best use of life is to spend it for something that outlasts it',
  'If you think education is expensive, try ignorance',
  'Entrepreneurship is living a few years of your life like most people wont so you can spend the rest of your life like most people can’t',
  'Lend your friend $20, if he doesn’t pay you back then he’s not your friend. Money well spent',
  'Be nice to geek’s, you’ll probably end up working for one',
  'To never forget that the most important thing in life is the quality of life we lead',
  'Its better to own the racecourse then the race horse',
  'When you go to buy, don’t show your silver',
  'It’s easier to ask forgiveness than it is to get permission',
  'To win without risk is to triumph without glory',
  'Example is not the main thing in influencing other people; it’s the only thing',
  'Associate yourself with people of good quality, for it is better to be alone than in bad company',
  'Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great',
  'There is only one success',
  'You don’t buy a nice car and get rich you get rich and buy a nice car',
  'Fall seven times, stand up eight',
  'One day your life will flash before your eyes. Make sure it is worth watching',
  'Whatever the mind can conceive and believe, the mind can achieve',
  'I have not failed. I’ve just found 10,000 ways that won’t work',
  'If you ain’t making waves, you ain’t kickin’ hard enough',
  'What is not started will never get finished',
  'Do not wait to strike until the iron is hot; but make it hot by striking',
  'When you cease to dream you cease to live',
  'There are two rules for success. 1) Never tell everything you know.',
  'The only place where success comes before work is in the dictionary.',
  'Every single person I know who is successful at what they do is successful because they love doing it.',
  'Being realistic is the most commonly traveled road to mediocrity.',
  'Whenever an individual or a business decides that success has been attained, progress stops.',
  'To be successful, you have to have your heart in your business, and your business in your heart.',
  'If hard work is the key to success, most people would rather pick the lock.',
  'Success is simply a matter of luck. Ask any failure.',
  'The road to success is always under construction.',
  'Anything the mind can conceive and believe, it can achieve.',
  'Most great people have attained their greatest success just one step beyond their greatest failure.',
  'Whether you think you can or you can’t, you’re right.',
  'Failure defeats losers, failure inspires winners.',
  'I have not failed. I’ve just found 10,000 ways that won’t work.',
  'The biggest failure you can have in life is not trying at all.',
  'I honestly think it is better to be a failure at something you love than to be a success at something you hate.',
  'Leaders don’t force people to follow, they invite them on a journey.',
  'Example is not the main thing in influencing other people; it’s the only thing.',
  'Leadership is doing what is right when no one is watching.',
  'Leadership is the art of getting someone else to do something you want done because he wants to do it.',
  'The difference between a boss and a leader: a boss says, ‘Go!’ -a leader says, ‘Let’s go!’.',
  'I am more afraid of an army of one hundred sheep led by a lion than an army of one hundred lions led by a sheep.',
  'The whole problem with the world is that fools and fanatics are always so certain of themselves, but wiser people so full of doubts.',
  'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
  'Cannibals prefer those who have no spines.',
  'A ship in harbor is safe. But that’s now what ships are built for.',
  'If one does not know to which port one is sailing, no wind is favorable.',
  'You miss 100% of the shots you don’t take.',
  'I’m not a businessman. I’m a business, man.',
  'The vision must be followed by the venture. It is not enough to stare up the steps – we must step up the stairs.',
  'Do not wait to strike until the iron is hot; but make it hot by striking.',
  'It’s easier to ask forgiveness than it is to get permission.',
  'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.',
  'One day your life will flash before your eyes. Make sure it is worth watching.',
  '“I think it’s wrong that only one company makes the game Monopoly.',
  'Ever notice how it’s a penny for your thoughts, yet you put in your two-cents? Someone is making a penny on the deal.',
  'Catch a man a fish, and you can sell it to him. Teach a man to fish, and you ruin a wonderful business opportunity.',
  'I used to sell furniture for a living. The trouble was, it was my own.',
  'Marking dynamos for repair $10,000.00—2 hours labor $10.00; knowing where to mark $9,990.00.',
  'By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.',
  'My son is now an ‘entrepreneur’. That’s what you’re called when you don’t have a job.',
  'I didn’t go to college, but if I did, I would’ve taken all my tests at a restaurant, ’cause ‘The customer is always right.’',
  'Formal education will make you a living. Self education will make you a fortune.',
  'The greatest reward in becoming a millionaire is not the amount of money that you earn. It is the kind of person that you have to become to become a millionaire in the first place.',
  'If you’re not learning while you’re earning, you’re cheating yourself out of the better portion of your compensation.',
  'A business that makes nothing but money is a poor business.',
  'After a certain point, money is meaningless. It ceases to be the goal. The game is what counts.',
  'I treat business a bit like a computer game. I count money as points. I’m doing really well: making lots of money and lots of points.',
  'All of my friends were doing babysitting jobs. I wanted money without the job.',
  '“I don’t pay good wages because I have a lot of money; I have a lot of money because I pay good wages.',
  'Lend your friend $20. If he doesn’t pay you back then he’s not your friend. Money well spent.',
  'Money and success don’t change people; they merely amplify what is already there.',
  'The secret of getting ahead is getting started.',
  'Hire character. Train skill.',
  'In preparing for battle I have always found that plans are useless, but planning is indispensable.',
  'You’ve got to stop doing all the things that people have tried, tested, and found out don’t work.',
  'I never perfected an invention that I did not think about in terms of the service it might give others… I find out what the world needs, then I proceed to invent.',
  'If you’re not making mistakes, then you’re not making decisions.',
  'Your most unhappy customers are your greatest source of learning.',
  'One can get anything if he is willing to help enough others get what they want.',
  'An entrepreneur tends to bite off a little more than he can chew hoping he’ll quickly learn how to chew it.',
  'The true entrepreneur is a doer, not a dreamer.',
  'Whenever you are asked if you can do a job, tell ’em, ‘Certainly, I can!’ Then get busy and find out how to do it.',
  'Everything started as nothing.',
  'If you start with nothing and end up with nothing, there’s nothing lost.',
  'Start today, not tomorrow. If anything, you should have started yesterday.',
  'Make it happen now, not tomorrow. Tomorrow is a loser’s excuse.',
  'Every day I get up and look through the Forbes list of the richest people in America. If I’m not there, I go to work.',
  'Entrepreneurship is living a few years of your life like most people won’t, so that you can spend the rest of your life like most people can’t.',
  'Yesterday’s home runs don’t win today’s games.',
  'You should always stay hungry. Stay hungry, so you can eat.',
  'If you’re not living life on the edge, you’re taking up too much space.',
  'I wasn’t satisfied just to earn a good living. I was looking to make a statement.',
  'Opportunity is missed by most people because it is dressed in overalls and looks like work.',
  'You must either modify your dreams or magnify your skills.',
  'Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.',
  'Not a single person whose name is worth remembering lived a life of ease.',
  'If you think that you are going to love something, give it a try. You’re going to kick yourself in the butt for the rest of your life if you don’t.',
  'The best time to plant a tree is twenty years ago. The second best time is now.',
  'If you want one year of prosperity, grow grain. If you want ten years of prosperity, grow trees. If you want one hundred years of prosperity, grow people.',
  'Vision without action is a daydream. Action without vision is a nightmare.',
  'Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character; sow a character, reap a destiny.',
  'A bad workman blames his tools.',
  'A fall into a ditch makes you wiser.',
  'Defeat isn’t bitter if you don’t swallow it.',
  'The diamond cannot be polished without friction, nor the man perfected without trials.',
  'A jade stone is useless before it is processed; a man is good-for-nothing until he is educated.',
  'A journey of a thousand miles begins with a single step.',
  'The loftiest towers rise from the ground.',
  'Building a castle is difficult. Defending and maintaining it is harder still.',
  'A person who says it cannot be done should not interrupt the man doing it.',
  'All cats love fish but fear to wet their paws.',
  'Don’t stand by the water and long for fish; go home and weave a net.',
  'Everyone should carefully observe which way his heart draws him, and then choose that way with all his strength.',
  'Failing to plan is planning to fail.',
  'If you pay peanuts, you get monkeys.',
  'Make happy those who are near, and those who are far will come.',
  'Teachers open the door. You enter by yourself.',
  'Find a job you love and you’ll never work a day in your life.',
  'The entrepreneur builds an enterprise; the technician builds a job.',
  'If you want to be inventive, you have to be willing to fail.',
  'The challenge is not just to build a company that can endure; but to build one that is worthy of enduring.',
  'Success is a lousy teacher. It seduces smart people into thinking they can’t lose.',
  'Don’t treat your customers like a bunch of purses and wallets.',
  'Nine out of ten businesses fail; so I came up with a foolproof plan',
  'I’m not a businessman',
  'If plan ‘A’ fails',
  'We make a living by what we get. But we make a life by what we give.',
  'Believe that you will succeed',
  'Victory comes only after many struggles and countless defeats.',
  'As long as you’re going to be thinking anyway, think big.',
  'Success is how high you bounce after you hit bottom',
  'Remembering you are going to die is the best way I know to avoid the trap of thinking you have something to lose.',
  'It’s not about how to get started; its about how to get noticed.',
  'A ship in harbor is safe, but that’s not what ships are for.',
  'If I find 10,000 ways something won’t work, I haven’t failed. I am not discouraged, because every wrong attempt discarded is often a step forward.',
  'Business opportunities are like buses, there’s always another one coming.',
  'If we don’t allow ourselves to make mistakes, we will never invest in things that are radical.',
  'The critical ingredient is getting off your butt and doing something.',
  'Nothing will work unless you do.',
  'Try not to be a man of success, but rather try to become a man of value.',
  'You won’t get anything unless you have the vision to imagine it.',
  'A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.',
  'In the modern world of business, it is useless to be a creative, original thinker unless you can also sell what you create.',
  'Success is doing what you want, where you want, when you want, with whom you want as much as you want.',
  'If you don’t have a competitive advantage',
  'You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.',
  'If everything seems under control, you’re just not going fast enough.',
  'Don’t be trapped by dogma',
  'Do or do not. There is no try.',
  'Show me a person who never made a mistake, and I will show you a person who never did anything.',
  'Ideas are commodity. Execution of them is not.',
  'User experience is everything. It always has been, but it’s undervalued and underinvested in. If you don’t know user-centered design, study it. Hire people who know it. Obsess over it. Live and breathe it. Get your whole company on board.',
  'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.',
  'The man who does not work for the love of work but only for money is likely to neither make money nor find much fun in life.',
  'Be undeniably good. No marketing effort or social media buzzword can be a substitute for that.',
  'Ideas are easy. Implementation is hard.',
  'You can say anything to anyone, but how you say it will determine how they will react.',
  'Always deliver more than expected.',
  'Assume you have 90 seconds with a new user before they decide to use your app or delete it.',
  'Even if you don’t have the perfect idea to begin with, you can likely adapt.',
  'Make your team feel respected, empowered and genuinely excited about the company’s mission.',
  'Stay self-funded as long as possible.',
  'In between goals is a thing called life, that has to be lived and enjoyed.',
  'Wonder what your customer really wants? Ask. Don’t tell.',
  'When times are bad is when the real entrepreneurs emerge.',
  'What do you need to start a business? Three simple things: know your product better than anyone, know your customer, and have a burning desire to succeed.',
  'Get big quietly, so you don’t tip off potential competitors.',
  'Don’t worry about failure; you only have to be right once.',
  'Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma',
  'Don’t be cocky. Don’t be flashy. There’s always someone better than you.',
  'Don’t take too much advice. Most people who have a lot of advice to give — with a few exceptions — generalize whatever they did. Don’t over-analyze everything. I myself have been guilty of over-thinking problems. Just build things and find out if they work.',
  'Openly share and talk to people about your idea. Use their lack of interest or doubt to fuel your motivation to make it happen.',
  'How you climb a mountain is more important than reaching the top.',
  'Associate yourself with people of good quality, for it is better to be alone than in bad company.',
  'It’s fine to celebrate success but it is more important to heed the lessons of failure.',
  'It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you’ll do things differently.',
  'Statistics suggest that when customers complain, business owners and managers ought to get excited about it. The complaining customer represents a huge opportunity for more business.',
  'There is only one success- to be able to spend your life in your own way.',
  'Formal education will make you a living; self-education will make you a fortune.',
  'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.',
  'Rarely have I seen a situation where doing less than the other guy is a good strategy.',
  'You miss 100 percent of the shots you don’t take.',
  'The best time to plant a tree was 20 years ago. The second best time is now.',
  'The secret to successful hiring is this: look for the people who want to change the world.',
  'Twenty years from now, you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.',
  'If you’ve got an idea, start today. There’s no better time than now to get going. That doesn’t mean quit your job and jump into your idea 100% from day one, but there’s always small progress that can be made to start the movement.',
  'It’s almost always harder to raise capital than you thought it would be, and it always takes longer. So plan for that.',
  'For all of the most important things, the timing always sucks. Waiting for a good time to quit your job? The stars will never align and the traffic lights of life will never all be green at the same time. The universe doesn’t conspire against you, but it doesn’t go out of its way to line up the pins either. Conditions are never perfect. “Someday is a disease that will take your dreams to the grave with you. Pro and con lists are just as bad. If it’s important to you and you want to do it “eventually, just do it and correct course along the way.',
  'I don’t have big ideas. I sometimes have small ideas, which seem to work out.',
  'Fail often so you can succeed sooner.',
  'When you cease to dream you cease to live.',
  'Whatever the mind can conceive and believe, the mind can achieve.',
  'Running a start-up is like eating glass. You just start to like the taste of your own blood.',
  'My number one piece of advice is: you should learn how to program.',
  'The way to get started is to quit talking and begin doing.',
  'The pace of change for entrepreneurs is rapidly accelerating, and the cost and risk of launching a new business and getting off the ground is just amazing. The ability to gain user feedback really quickly and adapt to what your consumers want is totally different with the web as it is now. But finding a new market, helping people and taking that original idea and turning it into a business is really exciting right now.',
  'Building and hanging on to an audience is the biggest role of social media.',
  'Every feature has some maintenance cost, and having fewer features lets us focus on the ones we care about and make sure they work very well.',
  'A poorly implemented feature hurts more than not having it at all.',
  'the entrepreneur always searches for change, responds to it, and exploits it as an opportunity.',
  'You don’t learn to walk by following rules. You learn by doing and falling over.',
  'The fastest way to change yourself is to hang out with people who are already the way you want to be.',
  'Risk more than others think is safe. Dream more than others think is practical.',
  'You shouldn’t focus on why you can’t do something, which is what most people do. You should focus on why perhaps you can, and be one of the exceptions.',
  'The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer not a dreamer.',
  'If you cannot do great things, do small things in a great way.',
  'Success is not what you have, but who you are.',
  'One of the huge mistakes people make is that they try to force an interest on themselves. You don’t choose your passions; your passions choose you.',
  'Lots of companies don’t succeed over time. What do they fundamentally do wrong? They usually miss the future.',
  'It takes humility to realize that we don’t know everything, not to rest on our laurels and know that we must keep learning and observing. If we don’t, we can be sure some startup will be there to take our place.',
  'There’s an entrepreneur right now, scared to death, making excuses, saying, ‘It’s not the right time just yet.’ There’s no such thing as a good time. Get out of your garage and go take a chance, and start your business.',
  'Be really picky with your hiring, and hire the absolute best people you possibly can. People are the most important component of almost every business, and attracting the best talent possible is going to make a huge difference.',
  'Worry about being better; bigger will take care of itself. Think one customer at a time and take care of each one the best way you can.',
  'You have a viable business only if your product is either better or cheaper than the alternatives. If it’s not one or the other, you might make some money at first, but it’s not a sustainable business.',
  'Every time I took these bigger risks, the opportunity for a bigger payout was always there.',
  'If you can do something to get somebody excited — not everybody — but if you can be the best for somebody, then you can win.',
  'Would you like me to give you a formula for success? It’s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success.',
  'People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'The successful warrior is the average man, with laser-like focus.',
  'Fall seven times and stand up eight.',
  'The successful man is the one who finds out what is the matter with his business before his competitors do.',
  'There’s no shortage of remarkable ideas, what’s missing is the will to execute them.',
  'Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.',
  'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.',
  'Everyone is a genius. But if you judge a fish by its ability to climb a tree, it will spend its whole life believing it is stupid.',
  'Success in business requires training and discipline and hard work. But if you’re not frightened by these things, the opportunities are just as great today as they ever were.',
  'It is never too late to be what you might have been.',
  'I am not a product of my circumstances. I am a product of my decisions.',
  'There is only one way to avoid criticism: Do nothing, say nothing, and be nothing.',
  'Build your own dreams, or someone else will hire you to build theirs.',
  'You may be disappointed if you fail, but you are doomed if you don’t try.',
  'I learned not to worry so much about the outcome, but to concentrate on the step I was on and to try to do it as perfectly as I could when I was doing it.',
  '"Do, or do not. There is no try."',
  '"Listen to them. Children of the night. What music they make."',
  '"It\'s alive! It\'s alive!"',
  '"Oh, no, it wasn\'t the airplanes. It was Beauty killed the Beast."',
  '"Magic Mirror on the wall, who is the fairest one of all?"',
  '"Elementary, my dear Watson."',
  '"I\'ll get you, my pretty, and your little dog, too!"',
  '"After all, tomorrow is another day!"',
  '"Frankly, my dear, I don\'t give a damn."',
  '"Toto, I\'ve got a feeling we\'re not in Kansas anymore."',
  '"There\'s no place like home."',
  '"As God is my witness, I\'ll never be hungry again."',
  "\"It's gone forever, that funny young, lost look I loved won't ever come back. I killed that when I told you about Rebecca. It's gone. In a few hours, you've grown so much older.\"",
  '"Here\'s looking at you, kid."',
  '"Play it, Sam. Play \'As Time Goes By."',
  '"We\'ll always have Paris."',
  '"Round up the usual suspects."',
  '"This is the beginning of a beautiful friendship."',
  '"When it comes to women, you’re a true democrat."',
  '"I am big! It\'s the pictures that got small."',
  '"Nobody ever lies about being lonely."',
  '"You don\'t understand! I coulda had class. I coulda been a contender. I could\'ve been somebody, instead of a bum, which is what I am."',
  '"Where we\'re going, we don\'t need roads"',
  '"Life is a banquet, and most poor suckers are starving to death!"',
  '"Well nobody is perfect"',
  '"My name is Bond, James Bond."',
  '"Bond. James Bond"',
  '"I don\'t understand. He meets a girl that can give him a new life and he pushes her away? Because he doesn\'t know how to love."',
  '"You expect me to talk? No, Mr Bond, I expect you to die!"',
  '"A martini. Shaken, not stirred."',
  '"Gentlemen, you can\'t fight in here! This is the War Room!"',
  '"What we\'ve got here is a failure to communicate."',
  '"They call me Mister Tibbs!"',
  '"Mrs. Robinson, you\'re trying to seduce me. Aren\'t you?"',
  '"You only live twice: Once when you are born and once when you look death in the face"',
  '"We rob banks."',
  '"Hello, gorgeous."',
  '"Love means never having to say you\'re sorry"',
  '"Public opinion has a way of changing."',
  '"Drop the gun, take the cannoli."',
  '"A man who doesn\'t spend time with his family can never be a real man."',
  '"I\'m going to make him an offer he can\'t refuse."',
  '"Great men are not born great, they grow great."',
  '"I\'m gonna make him an offer he can\'t refuse"',
  '"Father Dyer: My idea of Heaven is a solid white nightclub with me as a headliner for all eternity, and they LOVE me!!"',
  '"Men, you are about to embark on a great crusade to stamp out runaway decency in the west. Now you men will only be risking your lives, whilst I will be risking an almost certain Academy Award nomination for Best Supporting Actor."',
  "\"What did you expect? 'Welcome, sonny'? 'Make yourself at home'? 'Marry my daughter'? You've got to remember that these are just simple farmers. These are people of the land. The common clay of the new West. You know... morons.\"",
  '"Wait Master, it might be dangerous... you go first."',
  '"What\'s a dazzling urbanite like you doing in a rustic setting like this?"',
  '"Please! Remain in your seats, I beg you! We are not children here, we are scientists! I assure you there is nothing to fear!"',
  '"Keep your friends close, but your enemies closer."',
  "\"Now I don't have to tell you good folks what's been happening in our beloved little town. Sheriff murdered, crops burned, stores looted, people stampeded, and cattle raped. The time has come to act, and act fast. I'm leaving.\"",
  '"You\'re gonna need a bigger boat."',
  '"We are the Knights who say... Ni!"',
  '"It’s just a flesh wound."',
  '"Run Away!"',
  '"Yeah, to you, it\'s Thanksgiving; to me, it\'s Thursday."',
  '"You talking to me?"',
  '"Yo, Adrian!!."',
  '"Is it safe?"',
  '"If you strike me down, I shall become more powerful than you could possibly imagine."',
  '"It\'ll be just like Beggar\'s Canyon, back home"',
  '"May the Force be with you."',
  '"May the force be with you"',
  '"When I left you I was but the learner. Now I am the master."',
  '"That’s no moon…it’s a space station"',
  '"All right, but apart from the sanitation, medicine, education, wine, public order, irrigation, roads, the fresh water system and public health, what have the Romans ever done for us?"',
  "\"Oh! It's blessed are the meek! I'm glad they're getting something, they had a hell of a time...\"",
  '"Always look on the Bright Side of Life ... Always look on the Light Side of Life."',
  '"I love the smell of napalm in the morning"',
  '"Choose the sword, and you will join me. Choose the ball and you join your mother, in death. You don’t understand my words, but you must choose. So… come boy, choose life or death."',
  '"Joey, have you ever been in a turkish prison?"',
  '"Looks like I picked the wrong week to quit sniffing glue."',
  '"You must unlearn what you have learned."',
  "\"Little pigs, little pigs, let me come in! Not by the hair on your chinny chin chin? Then I'll huff... And I'll puff... And I'll blow your house in!\"",
  '"Do, or do not. There is no \'try\'."',
  '"Luke, I am your father."',
  '"Here\'s Johnny!"',
  '"It\'s not the years, honey. It\'s the mileage."',
  '"The sun will come out tomorrow."',
  "\"If you don't eat your meat, you can't have any pudding! How can you have any pudding if you don't eat your meat?!\"",
  '"I\'ve seen things you people wouldn\'t believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. All those moments will be lost in time, like tears in rain."',
  '"I changed the conditions of the test. I don’t like to lose."',
  '"Leaping lizards!"',
  '"Go ahead, make my day."',
  '"Say hello to my little friend!"',
  '"It’s a trap!"',
  '"I always tell tell the truth, even when i lie."',
  '"I am a Jedi, like my father before me."',
  '"From now on we are enemies, you and I."',
  '"I\'ll be back."',
  '"Hasta la Vista, baby."',
  '"I can’t believe I just gave my panties to a geek."',
  '"Are you telling me that you built a time machine out of a DeLorean."',
  '"I feel the need for speed"',
  '"I feel the need - the need for speed!."',
  '" I feel the need!!!! The need for speed!!!!"',
  '"It\'s only forever, not long at all..."',
  '"Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it."',
  '"I\'m a mog: half man, half dog. I\'m my own best friend!"',
  '"Snap out of it!"',
  "\"Come on... Come on! Do it! Do it! Come on. Come on! Kill me! I'm here! Kill me! I'm here! Kill me! Come on! Kill me! I'm here! Come on! Do it now! Kill me!\"",
  '"You idiots! These are not them! You\'ve captured their stunt doubles!"',
  '"So, Lone Starr, now you see that evil will always triumph because good is dumb."',
  '"And to think I\'ve been telling my friends it\'s so cool living with an artist. You never once asked to paint me nude!"',
  '"Nobody puts Baby in a corner."',
  '"Here endeth the lesson."',
  '"Death cannot stop true love"',
  '"As you wish..."',
  '"Hello. My name is Inigo Montoya. You killed my father. Prepare to die."',
  '"Inconcievable!"',
  '"Greed, for lack of a better word, is good"',
  '"Yippie-ki-yay, motherf—er!"',
  '"Welcome to the party, pal!"',
  '"Like a midget at a urinal, I was going to have to stay on my toes."',
  '"Say it aint’ so, Joe. Say it ain’t so."',
  '"I\'m not bad. I\'m just drawn that way."',
  '"Strange things are afoot at The Circle K."',
  '"You must strive to find your own voice because the longer you wait to begin, the less likely you are going to find it at all."',
  '"When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible."',
  '"Have you ever danced with the devil in the pale moonlight?"',
  '"I\'ll have what she\'s having."',
  '"If you build it, he will come."',
  '"Why don\'t you make like a tree and get out of here."',
  '"Carpe diem. Seize the day, boys. Make your lives extraordinary."',
  '"Just when I thought I was out, they pull me back in."',
  '"Never rat on your friends and always keep your mouth shut"',
  '"I love you. I really love you. Ditto."',
  '"I’m funny how?  Funny, like, I’m a clown?  I amuse you?"',
  '"This valley is just one long smorgasbord."',
  '"As far back as I can remember, I always wanted to be a gangster."',
  '"Better dead and cool then alive and uncool."',
  "\"You're a... you're a complex Freudian hallucination having something to do with my mother and I don't know why you have wings, but you have very lovely legs and you're a very nice tiny person and what am I saying? I don't know who my mother was. I'm an orphan and I've never taken drugs because I missed the sixties; I was an accountant.\"",
  '"Oh, and Senator, just one more thing. Love your suit."',
  '"Hook, you let those kids out of that net in less than one minute or you better get an attorney and hope to God he\'s better than me."',
  '"Hasta la vista, baby."',
  '"And you\'d better deliver, Miss Bell, or no amount of clapping will bring you back from where I will send you."',
  "\"Of course it's hard. It's supposed to be hard. If it wasn't hard, everyone would do it. The hard is what makes it great\"",
  '"There\'s no crying in baseball!"',
  '"You can\'t handle the truth!"',
  '"Party on, Wayne! Party on, Garth!"',
  '"You shoot me in a dream, you better wake up and apologise."',
  '"You\'re killing me, smalls!"',
  '"Life, uh, finds a way."',
  '"Clever girl."',
  '"What do you call them, Max? Yabbos? Max likes your yabbos. In fact, he loves them!"',
  '"You bred raptors?"',
  '"I\'m your Huckleberry."',
  '"You’re killin’ me, Smalls."',
  '"When I got tired, I slept. When I got hungry, I ate. When I had to go, you know, I went."',
  '"Some birds aren\'t meant to be caged. Their feathers are just too bright."',
  '"Yeah I called her up. She gave me a bunch of crap about me not listening to her, or something. I don\'t know, I wasn\'t really paying attention."',
  '"Run, Forrest, run!"',
  '"Lord, it\'s a miracle! Man up and vanished like a fart in the wind!"',
  '"The past can hurt. But the way I see it, you can either run from it or learn from it."',
  '"Oh yes, the past can hurt. But you can either run from it, or learn from it."',
  '"Hope is a good thing, maybe the best of things, and no good thing ever dies."',
  '"Everything the light touches is our kingdom."',
  '"Life is like a box of chocolates; you never know what you\'re gonna get."',
  '"These walls are funny. First you hate ’em. Then you get used to ’em. Enough time passes, you get so you depend on them. That’s institutionalized."',
  '"I mean, seriously, how often do you really look at a mans shoes?"',
  '"Hope is a good thing, maybe the best of things, and no good thing ever dies."',
  '"Everything you see exists together in a delicate balance. As king, you need to understand that balance and respect all the creatures, from the crawling ant to the leaping antelope."',
  '"Mama says stupid is as stupid does."',
  '"For you, the day Bison graced your village, was the most important day in your life. But for me, it was Tuesday."',
  '"Salvation lies within."',
  '"Hakuna matata"',
  '"Don\'t ever let anybody tell you they’re better than you."',
  '"Mama always said life was like a box of chocolates. You never know what you\'re gonna get."',
  '"Is life always this hard, or is it just when you\'re a kid?"',
  '"They may take our lives, but they\'ll never take our freedom!"',
  '"Houston, we have a problem."',
  '"Hack the planet."',
  '"What\'s in the box?!"',
  '"They may take our lives, but they\'ll never take our freedom!"',
  '" I used to think that if none of your family or friends knew you were dead, it was like not really being dead. People can invent the best and the worst for you."',
  '"The greatest trick the devil ever pulled was convincing the world he didn\'t exist."',
  '"Bye Felicia!"',
  '"Every man dies; not every man really lives."',
  '"This isn\'t flying. This is falling with style!"',
  '"To infinity and beyond!"',
  '"That\'ll do, pig. That\'ll do."',
  '"Get on the scale! Get off the scale!"',
  '"Every man dies, but not every man really lives."',
  '"You can trouble me for a warm glass of SHUT THE HELL UP!! Now you will go to sleep or I will put you to sleep."',
  '"Show me the money!"',
  '"You had me at hello."',
  '"You little son of a bitch ball! Why you don\'t you just go HOME? That\'s your HOME! Are you too good for your HOME? ANSWER ME! SUCK MY WHITE ASS, BALL!"',
  '"Some people can’t believe in themselves until someone else believes in them first."',
  '"Ain\'t no rules says a dog can\'t play basketball."',
  '"Does anything more dangerous than that lurk just beneath the surface?"',
  '"You make me want to be a better man."',
  '"I\'m king of the world!"',
  '"Draw me like one of your French girls"',
  '"Tonight\'s forecast: a freeze is coming!"',
  '"People live their lives bound by what they accept as correct and true. That\'s how they define "reality". But what does it mean to be "correct" or "true"? Merely vague concepts... Their "reality" may all be a mirage. Can we consider them to simply be living in their own world, shaped by their beliefs?"',
  '"My Mama says that alligators are ornery because they got all them teeth and no toothbrush."',
  '"What I need is a real, live ghost. That\'s an oxymoron, Daph."',
  '"You can feel the chill in the air, cut, who opened a window?"',
  '"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti."',
  '"No matter how the wind howls, the mountain cannot bow to it."',
  '"I’m the Dude, so that’s what you call me. That or, uh His Dudeness, or uh Duder, or El Duderino, if you’re not into the whole brevity thing."',
  '"Zoinks! How humiliating! Chased into a hole by 1/3 of a B.L.T.!"',
  '"Make the money. Don’t let it make you."',
  '"Wipe your upper lip, romeo."',
  '"Put the weed in the bag first, then get money."',
  '"A single grain of rice can tip the scale. One man may be the difference between victory and defeat."',
  '"You\'re taking all the caviar? That caviar is a garnish!"',
  '"The flower that blooms in adversity is the most rare and beautiful of all."',
  '"Like... we\'re not looking for any ghoul-friends, are we, Scooby?"',
  '"I\'m having an old friend for dinner."',
  '"I live in Notting Hill. You live in Beverly Hills. Everyone in the world knows who you are, my mother has trouble remembering my name."',
  '"I\'m also just a girl, standing in front of a boy, asking him to love her."',
  '"Time is always against us."',
  '"The things you used to own, now they own you."',
  '"Don\'t touch my nakama(friend) anymore! "',
  '"It’s only after we’ve lost everything that we’re free to do anything."',
  '"Don’t let anyone ever make you feel like you don’t deserve what you want."',
  '"Unfortunately, no one can be told what the Matrix is. You have to see it for yourself."',
  '"Ignorance Is Bliss"',
  '"I see dead people."',
  '"The first rule of Fight Club is: You do not talk about Fight Club."',
  '"There is a difference between knowing the path and walking the path."',
  "\"It's only after we've lost everything that we're free to do anything.\"",
  '" I was the warm little center that the life of this world crowded around."',
  '"Fear. Fear attracts the fearful… the strong… the weak… the innocent… the corrupt. Fear. Fear is my ally."',
  '"By Grabthar\'s hammer...what a savings."',
  '"Stop trying to control everything and just let go! LET GO!"',
  '"Miracles only happen to those who never give up"',
  '"You met me at a very strange time in my life"',
  '"I know kung fu."',
  '"People hurt the ones they love. That\'s how it is all around the world"',
  '"We need guns. Lots of guns."',
  '"Damn! We\'re in a tight spot!"',
  '"Are you not entertained?"',
  '"They called me Mr. Glass."',
  '"I hope he didn’t die. Unless he left a note naming me his successor, then I hope he did die."',
  '"There are No Accidents. No Coincidences. No Escapes. YOU CAN\'T CHEAT DEATH."',
  '"Dude, where\'s my car?"',
  '"Do you know what happens to a toad when it\'s struck by lightning? The same thing that happens to everything else."',
  '"Your eyes are like two big blue eyes."',
  '"The key to a woman\'s heart is an unexpected gift at an unexpected time."',
  '"I\'ll take poor assumptions for $800, Alex."',
  '"Wilsoooooon."',
  '"Wilma, whatever you decide to do, I want you to know something. Your daddy will always love you."',
  '"Oh Fred. That\'s so sweet."',
  '"If you utter so much as one syllable, I\'LL HUNT YOU DOWN AND GUT YOU LIKE A FISH! If you\'d like to fax me, press the star key."',
  '"My name is Maximus Decimus Meridius, commander of the Armies of the North, General of the Felix Legions and loyal servant to the true emperor, Marcus Aurelius. Father to a murdered son, husband to a murdered wife. And I will have my vengeance, in this life or the next."',
  '"No thinking -- that comes later. You must write your first draft with your heart. You rewrite with your head. The first key to writing is... to write, not to think!"',
  '"We could not talk or talk forever and still find things to not talk about."',
  '"Snnnnnooooooooooow!!!!!!!!!"',
  '"I\'ve gotta get out of this place. Someday I\'m getting on that train."',
  '"Yeah. We graduated high school. How totally amazing."',
  '"One can never have enough socks."',
  '"Just what do you think you\'re doing, Dave?"',
  '"You\'re a wizard, Harry."',
  '"You shall not pass!"',
  '"Ask any racer. Any real racer. It don\'t matter if you win by an inch or a mile. Winning\'s winning."',
  '"Even the smallest person can change the course of the future."',
  '"I live my life a quarter mile at a time."',
  '"They say that dreams are only real as long as they last. Couldn\'t you say the same thing about life?"',
  '"All we have to decide what to do with the time that is given to us."',
  '"Exercise gives you endorphins. Endorphins make you happy. Happy people just don\'t shoot their husbands. They just don\'t."',
  '"What is this? A center for ants?"',
  '"All we have to decide is what to do with the time that is given us."',
  '"Of the days that I have lived, only those I spent with you seemed real."',
  '"Ogres are like onions."',
  '"Once you meet someone, you never really forget them. It just takes a while for your memory to come back to you"',
  '"I don\'t know half of you half as well as I should like; and I like less than half of you half as well as you deserve."',
  '"The greatest thing you’ll ever learn is just to love and be loved in return."',
  '"It\'s only in the mysterious equation of love that any logical reasons can be found."',
  '"One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them."',
  '"Even the smallest person can change the course of history."',
  '"It’s a dangerous business, going out your door…You step into the Road, and if you don’t keep your feet, there is no knowing where you might be swept off to."',
  '"No, I like you very much, just as you are."',
  '"Welcome the rich man, he\'s hard for you to miss. His butt keeps getting bigger, so there\'s plenty there to kiss!"',
  '"Do you like dags?"',
  '"There’s some good in this world, and it’s worth fighting for."',
  '"I\'m tired of people who judge me without knowing my history."',
  '"I don\'t like sand. It\'s all coarse, and rough, and irritating. And it gets everywhere."',
  '"Your time will come. You will face the same Evil, and you will defeat it."',
  '"The battle of Helm\'s Deep is over; the battle for Middle Earth is about to begin. "',
  '"It is not our abilities that show what we truly are… it is our choices."',
  '"With great power comes great responsibility."',
  '"Dadinho é o caralho, meu nome é Zé Pequeno porra!"',
  '"There is always hope."',
  '"You know, I\'m something of a scientist myself."',
  '"My precious"',
  '"Li\'l dice my ass, my name is now Li\'l Zé now"',
  '"But in the end it’s only a passing thing, this shadow, even darkness must pass."',
  '"My precious..."',
  '"Dark have been my dreams of late."',
  '"It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends."',
  '"Even the smallest person can change the course of the future."',
  '"Ye best start believin\' in ghost stories, Miss Turner. Yer in one."',
  '"This is the day you will always remember as the day you almost caught Captain Jack Sparrow"',
  '"You sit on a throne of lies."',
  '"To me, you are perfect."',
  '"I will not say: do not weep; for not all tears are an evil."',
  '"I want to change things. I want to believe that anything can be changed. The moment I met you, a new world opened up for me. You see, after wandering in the darkness for so long, a light brought me happiness. It’s all thanks to you."',
  '"The thing about romance is people only get together right at the very end."',
  '"Why are you trying so hard to fit in when you were born to stand out?"',
  '"We\'re goin\' streaking!"',
  '" You\'re my boy, Blue!"',
  '"That there’s some good in this world, Mr. Frodo… and it’s worth fighting for."',
  '"Just keep swimming."',
  '"The problem is not the problem. The problem is your attitude about the problem. Do you understand?"',
  '"Not all treasure is silver and gold mate"',
  '"The ones that love us never really leave us."',
  '"Boo, you whore!"',
  '"I want to play a game."',
  "\"Stop trying to make 'fetch' happen. It's not going to happen.\"",
  '"It\'s like I have ESPN or something."',
  '"We should totally just stab Caesar!"',
  '"Whatever. I\'m getting cheese fries."',
  '"That is so fetch!"',
  '"You gonna eat your tots?"',
  '"You gotta hear this one song. It\'ll change your life, I swear."',
  '"A day may come when the courage of men fails… but it is not THIS day."',
  '"That\'s why her hair is so big.  It\'s full of secrets."',
  '"You\'ve got red on you"',
  '"Nobody makes me bleed my own blood. Nobody!"',
  '"I am gonna kill Bill."',
  '"Is butter a carb?"',
  '"I solemnly swear that I am up to no good."',
  '"I\'m not drinking any f****** Merlot!"',
  '"Your identity is your most valuable possession. Protect it."',
  '"Nunchuck skills… bowhunting skills… computer hacking skills… Girls only want boyfriends who have great skills!"',
  '"No, I shot him. Bullets and the fall killed him."',
  '"They’ve done studies, you know. 60% of the time, it works every time."',
  '"I wish I could bake a cake filled with rainbows and smiles and everyone would eat and be happy."',
  '"Four for you, Glen Coco! You go, Glen Coco!"',
  '"There\'s a 30% chance that it\'s already raining."',
  '"She doesn\'t even go here!"',
  '"You gotta hear this one song. It\'ll change your life, I swear."',
  '"I love lamp."',
  '"You have bewitched me, body and soul."',
  '"Life is a banquet, and most poor suckers are starving to death!"',
  '"And a hero is a person who resigns to be forgotten as we forget the dead for revolution."',
  '"If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals."',
  '"Did you ever hear the tragedy of Darth Plagueis The Wise? I thought not. It\'s not a story the Jedi would tell you. It\'s a Sith legend."',
  '"Why do we fall? So we can learn to pick ourselves up."',
  '"If you want to know what a man\'s like,take a good look at how he treats his inferiors."',
  '"Life is not the amount of breaths you take. It’s the moments that take your breath away."',
  '"I wish I knew how to quit you."',
  '"I am the senate!"',
  '"It\'s not who I am underneath, but what I do that defines me"',
  '"Didn\'t I tell you about the football field in the bathroom cupboard?"',
  '"Why do we fall sir? So that we can learn to pick ourselves up."',
  "\"What's comin' will come and we'll meet it when it does.\"",
  '"Happiness is the most insidious prison of all, Evey."',
  '"All\'s fair in Love and Basketball baby"',
  '"Be it a stone or a grain of sand, in water they both sink."',
  '"They don\'t know that we know they know we know."',
  '"That\'s what she said."',
  '"I\'m sorry father, for you there is only death. But our destiny is life!"',
  '"If you ain\'t first, you\'re last."',
  '"Walk that walk and go forward all the time. Don\'t just talk that talk, walk it and go forward. Also, the walk didn\'t have to be long strides; baby steps counted too. Go forward."',
  "\"I can't really remember when I last had any hope, and I certainly can't remember when anyone else did either. Because really, since women stopped being able to have babies, what's left to hope for?\"",
  "\"Y'know that ringing in your ears? That 'eeeeeeeeee'? That's the sound of the ear cells dying, like their swan song. Once it's gone you'll never hear that frequency again. Enjoy it while it lasts.\"",
  '"Life’s simple. You make choices and you don’t look back."',
  '"I\'m gonna say what any man with two penises would say when his tailor asks him if he dresses right or left... Yes."',
  "\"People can't do somethin' themselves, they wanna tell you you can't do it. If you want somethin', go get it. Period. \"",
  '"Speed. I am speed."',
  '"I\'m just one stomach flu away from my goal weight."',
  '"Float like a cadillac sting like a beemer."',
  '"The world is your oyester. It\'s up to you to find the pearls."',
  '"Florals? For Spring. Groundbreaking."',
  '"Nobody is gonna hit as hard as life, but it ain’t how hard you can hit. It’s how hard you can get hit and keep moving forward. It’s how much you can take, and keep moving forward. That’s how winning is done."',
  '"Very nice!"',
  '"I have had it with these motherfuckin\' snakes on this motherfuckin\' plane!"',
  '"Don’t ever let somebody tell you, you can’t do something. Not even me. Alright?"',
  '"Death is the road to awe."',
  '"The past can\'t hurt you anymore, unless you let it."',
  '"This is Sparta!"',
  '"That\'s the beauty of argument. When you argue correctly, you\'re never wrong."',
  '"Dear 8-pound, 6-ounce newborn infant Jesus..."',
  '"Are you watching closely?"',
  '"Dreams remind us what reality is."',
  "\"You got a dream... You gotta protect it. People can't do somethin' themselves, they wanna tell you you can't do it. If you want somethin', go get it. Period.\"",
  '"If we admit that human life can be ruled by reason, then all possibility of life is destroyed."',
  '"The woods are lovely, dark and deep, and I have promises to keep and miles to go before I sleep. Did you hear me butterfly? Miles to go before you sleep."',
  '"I read somewhere... how important it is in life not necessarily to be strong... but to feel strong."',
  '" Spider-Pig, Spider-Pig. Does whatever a Spider-Pig does. Can he swing from a web? No he can\'t, he\'s a pig. Look out! He is a Spider-Pig!"',
  '"When you want something in life, you just gotta reach out and grab it."',
  '"...And I also know how important it is in life not necessarily to be strong but to feel strong. To measure yourself at least once. To find yourself at least once in the most ancient of human conditions. Facing the blind death stone alone, with nothing to help you but your hands and your own head"',
  '"Anyway, my mum always said things we lose have a way of coming back to us in the end, if not always in the way we expect."',
  '"They all deserve to die. Even you, Mrs. Lovett. Even I. Because the lives of the wicked should be made brief. For the rest of us death would be relief."',
  '"As long as the concept of winners exists, there must also be losers."',
  '"We’ve all got both light and darkness inside us. What matters is the part we choose to act on. That’s who we really are."',
  '"Not anyone can become a great artist, but a great artist can come from anywhere."',
  '"Happiness is only real when shared"',
  '"What\'s the most you ever lost on a coin toss?"',
  '"There\'s no room for softness... not in Sparta. No place for weakness. Only the hard and strong may call themselves Spartans. Only the hard, only the strong."',
  '"I never realized how much I loved being home unless I\'d been somewhere really different for awhile."',
  '"We\'ve all got both light and darkness inside us. What matters is the part we choose to act on. That\'s who we really are."',
  '"These are desperate times, Mrs Lovett. And desperate measures are called for."',
  '"I\'m already pregnant. So, what other shenanigans could I get myself into?"',
  '"Music\'s the only thing that makes sense anymore, man. Play it loud enough, it keeps the demons at bay."',
  '"Some people feel like they don\'t deserve love. They walk away quietly into empty spaces, trying to close the gaps of the past."',
  '"But when you forgive, you love. And when you love, God\'s light shines through you."',
  '"Sometimes, informations is more dangerous than weapons"',
  "\" It's not about what I want. It's about what's fair!\"",
  '" About three things I was absolutely certain. First, Edward was a vampire. Second, there was part of him-and I didn\'t know how potent that part might be- that thirsted for my blood. and third, I was unconditionally and irrevocably in love with him."',
  '"Some men just want to watch the world burn. "',
  '"It is within my power to drastically change his cirumstances, but I don\'t want to give that man a gift he doesn\'t deserve."',
  '"I don\'t know what kind of gun this is. I only know the sound it makes when it kills a man."',
  '"Sometimes the truth isn’t good enough, sometimes people deserve more. Sometimes people deserve to have their faith rewarded    "',
  '"It\'s not about money...it’s about sending a message. Everything burns!"',
  '"If you let my daughter go now, that\'ll be the end of it. I will not look for you, I will not pursue you. But if you don\'t, I will look for you, I will find you, and I will kill you."',
  '"There is no secret ingredient. It’s just you."',
  '"Why so serious?"',
  '"You either die a hero, or you live long enough to see yourself become the villain."',
  '"Give me a scotch!"',
  '"I don\'t read the script. The script reads me."',
  '"Me? I know who I am. I\'m a dude playing a dude disguised as another dude."',
  '"May the odds ever be in your favor."',
  '"Don\'t talk like you\'re one of them"',
  '"Our lives are defined by opportunities, even the ones we miss."',
  '"You see, in their last moments people show you who they really are."',
  '"If you’re good at something, never do it for free."',
  '"I\'m not a big fat panda. I\'m THE big fat panda."',
  '"You either die a hero or live long enough to see yourself become the villian."',
  '"Let\'s put a smile on that face!"',
  '"I believe whatever doesn’t kill you, simply makes you stranger."',
  '"Is it better to be feared or respected? I say, is it too much to ask for both?"',
  '"Madness, as you know, is like gravity, all it takes is a little push."',
  '"I am not in danger, I am the danger"',
  '"Some men just want to watch the world burn."',
  '"Does it depress you? To know just how alone you really are?"',
  '"Do i look like a guy with plan?"',
  "\"It's not about what I want. It's about what's fair!\"",
  '"Nobody panics when things go “according to plan”. Even if the plan is horrifying!"',
  '"Adventure is out there"',
  '"Nobody knows this mall better than I do."',
  '"If what I think is happening is happening, it better not be."',
  '"I love you too, but I shouldn\'t have married you."',
  '"I love rumors! Facts can be so misleading, but rumors, true or false, are often revealing"',
  '"Just because she likes the same bizzaro crap you do doesn\'t mean she\'s your soul mate."',
  '"Didn\'t I tell you not to come to my house? Nobody touches my child!"',
  '"You\'ve ever been to Del Frisco\'s? They cater, so for lunch I would love a twenty ounce porterhouse steak, medium maybe a little charred, with all the trimmings pommes frites, asparagus, and butter squash."',
  "\"We're all different... Him, especially. But there's something kind of fantastic about that, isn't there?\"",
  '"It is impossible to manufacture or imitate love"',
  '"Every path is the right path. Everything could\'ve been anything else. And it would have just as much meaning."',
  '"Hell is a teenage girl."',
  '"It was my bad. I was never a very good practical joker."',
  '"This weapon seems made to order for the Brothers Grimm downstairs."',
  '"Am I being flirted with by a psychotic rat?"',
  '"Redemption? Sure. But in the end, he\'s just another dead rat in a garbage pail behind a Chinese restaurant."',
  '"What happens in vegas stays in vegas"',
  '"Whoops. Broke your 350 year old doorknob"',
  '"Which would be worse, to live a monster or die as a good man?"',
  '"You cocky cock! You\'ll pay for your crimes against humanity!"',
  '"You want to know the difference between a master and a beginner? The master has failed more times that the beginner has ever tried."',
  '"An idea is like a virus. Resilient. Highly contagious. And even the smallest seed of an idea can grow. It can grow to define or destroy you."',
  '"There\'s a benefit to losing: You get to learn from your mistakes."',
  '"A million dollars isn\'t cool. You know what\'s cool?"',
  '"It is a curious thing, Harry, but perhaps those who are best suited to power are those who have never sought it."',
  '"Dreams feel real while we\'re in them. It\'s only when we wake up that we realize something was actually strange."',
  '"You have nothing to fear, if you have nothing to hide."',
  '"Only he knew the price he paid, to become the greatest birder of all time."',
  '"Zaldrīzes buzdari iksos daor! (A dragon is not a slave!)"',
  '"I\'m so much better when you\'re around"',
  '"The problem is, I pretty much fancy everyone. It\'s like I\'ve just got out of prison all of the time."',
  '"When you play game of thrones, you win or you die, there is no middle ground!"',
  "\"A tortilla is either corn or wheat. But a corn tortilla folded and filled is a taco, whereas a filled wheat tortilla is a burrito. Deep fry a burrito, it's a chimichanga.Toast a tortilla, it's a tostada. Roll it, it's an enchilada.\"",
  '"No one should be immortal, if even one person has to die."',
  '"Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?"',
  '"The winter is coming."',
  '"Winter is coming!"',
  '"Chaos is a ladder!"',
  '"A Lannister always pays his debts"',
  '"You is kind. You is smart. You is important."',
  '"For a guy with a four digit IQ, I must have missed something."',
  '"Go to work and have a fun."',
  '"Hodor"',
  '"Never Stop Looking for What\'s Not There."',
  '"Cause if we can\'t protect the Earth, you can be damn sure we\'ll avenge it."',
  '"You had my curiosity. But now you have my attention."',
  '"Gentlemen, you had my curiosity, but now you have my attention."',
  '"There are those who say fate is something beyond our command, that destiny is not our own. But I know better. Our fate lives within us. You only have to be brave enough to see it."',
  '"Above all, don\'t lose hope"',
  '"That’s my secret, Captain. I’m always angry."',
  '"I\'m a huge fan of the way you lose control and turn into an enormous green rage monster."',
  '"Better clench up, Legolas."',
  '"Bright day uh, Bright Boy?"',
  '"Where there\'s life there\'s hope."',
  '"Ah you think darkness is your ally? You merely adopted the dark. I was born in it, molded by it. I didn\'t see the light until I was already a man, by then it was nothing to me but blinding"',
  '"Following\'s not really my style."',
  '"There was an idea to bring together a group of remarkable people, to see if we could become something more"',
  '" That\'s what I do: I drink and I know things."',
  '"Genius, billionaire, playboy, philanthropist."',
  '"I love you, but you don\'t know what you\'re talking about."',
  '"When you stop trying to force the solution, it\'ll happen on its own."',
  '"The law says that you cannot touch. But I think I see a lot of lawbreakers up in this house tonight"',
  '"We accept the love we think we deserve"',
  '"All The people I\'ve murdered by letting you live..."',
  '"Sometimes you gotta run before you can walk"',
  '"Look closer because the closer you think you are the less you actually see"',
  '"I have nothing to prove to you"',
  '"Let us learn to show our friendship for a man when he is alive and not after he is dead."',
  '"If wishes could be granted, if desires could be fulfilled, then I wouldn’t wish or desire for anything after all. The things you’re handed on a silver platter are never genuine, and never everlasting. And that is why I’ll always keep searching."',
  '"The people who are crazy enough to think that they can change the world, are the one\'s who do"',
  '"A wise man can learn more from his enemies than a fool from his friends."',
  '"There\'s no nobility in poverty."',
  '"You’ve changed, Bilbo Baggins. You’re not the same hobbit as the one who left the Shire."',
  '"I warned your grandfather of what his greed would summon, but he would not listen."',
  '"Let it go!"',
  '"Proximity to power deludes some into thinking they wield it."',
  '"Just remember: if you look in the face of evil, evil\'s gonna look right back at you."',
  '"The only thing we\'re allowed to believe is that we won\'t regret the choice we made."',
  '"You have got to be willing to crash and burn. If you are afraid of failing, you wont get very far"',
  '"It\'s the loneliest feeling not to know who you are"',
  '"I just try to live every day as if it was the final day of my extraordinary, ordinary life."',
  '"I don\'t want to survive. I want to live."',
  '"Look At Me, I\'m The Captain Now"',
  '"You don\'t turn your back on family, Even when they do"',
  '"I\'m not sure, about anything."',
  '"People don’t buy stock; it gets sold to them. Don’t ever forget that."',
  '"The heart is not like a box that gets filled up; it expands in size the more you love. I\'m different from you. This doesn\'t make me love you any less. It actually makes me love you more."',
  '"People who can’t throw something important away, can never hope to change anything."',
  '"Well, I don\'t want to survive. I want to live."',
  '"We\'re all traveling through time, together, everyday of our lives... All we can do is do our best to relish this remarkable life."',
  '"Rather than a person who hurts others, become the person getting hurt"',
  '"It\'s not magic, it\'s talent and sweat."',
  '"The truth is a matter of circumstances, it’s not all things to all people all the time."',
  '"Don\'t wait for things to get easier, simpler, better. Life will always be complicated. Learn to be happy right now. Otherwise, you\'ll run out of time."',
  '"Even a broken clock is right twice a day."',
  '"Not quite my tempo."',
  '"Popularity is the slutty little cousin of prestige."',
  "\"Look, you're beautiful and you're talented. And I'm lucky to have you.\"",
  '"One day it’ll grow, and every time I look at it, I’ll remember. Remember everything that happened: the good, the bad and how lucky I am that I made it home."',
  '"That’s what you always do, you confuse love for admiration."',
  '"If more people valued home above gold, this world would be a merrier place."',
  '"Only a fool argues for the pride of a dead man."',
  '"They never see you coming, do they Bob?"',
  '"Sometimes it is the people who no one imagines anything of who do the things that no one can imagine."',
  '"I am Groot."',
  '"The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can/\'t achieve it."',
  "\"So many times in my life I screwed up: I've talked when I should've listened, I've been harsh when I should've been tender.\"",
  '"Dragon sickness. I’ve seen it before. That look, the terrible need. It is a fierce and jealous love, Bilbo. It sent his grandfather mad."',
  "\"People keep asking if I'm back and I haven't really had an answer, but yeah, I'm thinking I'm back.\"",
  '"Do not go gentle into that good night. Rage, rage against the dying of the light."',
  '"There are no two words in the English language more harmful than good job."',
  '"You don\'t get to choose if you get hurt in this world,but you do have a say in who hearts you"',
  '"We used to look up at the sky and wonder at our place in the stars, now we just look down and worry about our place in the dirt."',
  '"The price of freedom is high, and it\'s the price I am willing to pay"',
  '"I\'m not going to launch those ships. Captain\'s orders."',
  '"Ideals are peaceful; history is violent."',
  '"Dress like a kingsman."',
  '"Nobody exists on purpose, nobody belongs anywhere, everybody\'s gonna die. Come watch TV?"',
  '"Wubba lubba dub dub!"',
  '"Having a family doesn’t mean that you stop being an individual. You know the best thing you can do for the people that depend on you? Be honest with them, even if it means setting them free."',
  '"There are no two words in the English language more harmful than good job"',
  '"Machines can never think as humans do but just because something thinks differently from you, does it mean it\'s not thinking?"',
  '"Pain demands to be felt"',
  '"I know it\'s not ordinary. But who ever loved ordinary?"',
  '"Were you rushing or were you dragging?"',
  '"No system is safe."',
  '"Everyone’s a whore, Grace. We just sell different parts of ourselves."',
  '"We are all different. However bad life may seem, there is always something you can do, and succeed at. While there\'s life, there is hope."',
  '"Come find me when you wake up!"',
  '"You never would have come here unless you believed you were going to save them. Evolution has yet to transcend that simple barrier. We can care deeply - selflessly - about those we know, but that empathy rarely extends beyond our line of sight."',
  '"This world’s a treasure, but it’s been telling us to leave for a while now."',
  '"A machine doesn\'t improvise well because you cannot program a fear of death. Our survival instinct is our greatest source of inspiration."',
  '"Not my tempo."',
  '"Mankind was born on Earth. It was never meant to die here."',
  '"Hardest time to lie to somebody is when they\'re expecting to be lied to."',
  '"Some infinities are bigger than other infinities."',
  '"If an angelic being fell from the sky and tried to live in this world of ours I think even they would commit many wrongs."',
  '"I\'m on a roller-coaster that only goes up, my friend."',
  "\"It's not because we can't take vengeance that we should feel sorry. The real reason to feel sorry... is when one is hung up on revenge and can't live their own life.\"",
  '"Sometimes it\'s people closest to us who lie to us best"',
  '"You become responsible, forever, for everything you tamed."',
  '"Mark Watney, Space Pirate."',
  '"How do you know the angel and the devil inside me aren’t the same thing?"',
  '"I am the scales of justice, conductor of the choir of death!"',
  '"Oh what a day. What a lovely day!"',
  '"Witness me!"',
  '"I\'m going to have to science the s*** out of this."',
  '"Just because someone stumbles and loses their path, doesn’t mean they’re lost forever."',
  '"Manners maketh man"',
  '"Haven\'t you ever wanted something so ba that it becomes more than a want?"',
  '"When I get back home, I want all the praise to go towards me."',
  '"What a treacherous thing to believe that a person is more than a person?"',
  '"Examined from another angle, your faults and weaknesses can be weapons"',
  '"People keeps secret computers don\'t"',
  '"That\'s not how the force works!"',
  '"But if you tame me, then we shall need each other, to me you shall be unique in all the world, to you i shall be unique."',
  '"Chewie, we\'re home."',
  '"My tastes are very singular."',
  '"It is only with the heart that one can see rightly; what is essential is invisible to the eye"',
  '"Like the oldman said, together"',
  '"Power belongs to those who take it."',
  '"That light saber was luke\'s, and his father\'s before him, and now it calls to you!"',
  '"I don\'t have friends. I got family."',
  '"A bit of madness is key"',
  '"Secrecy is security and security is victory."',
  '"Once in a while when I wake up. I find myself crying."',
  '"When life gets you down, you know what you gotta do? Just keep swimming."',
  '"Bombs won\'t stop terrorism, brains will, and we don\'t have nearly enough of those."',
  '"Marriage is buying a house for someone you hate"',
  '"At some point, you gotta decide for yourself who you gonna be. Can\'t let nobody make that decision for you."',
  '"Life’s a little bit messy. We all make mistakes. No matter what type of animal you are, change starts with you."',
  '"For Azeroth, for the Alliance!"',
  '"When you love someone, you work it out. You don\'t just throw it away. You have to be careful with it, you might never get it again."',
  "\"You're right, Aurora. But the drowning man will always try and drag somebody down with him. It ain't right, but the man's drowning.\"",
  '"Tell me... do you bleed? You will!"',
  '"You can’t buy love, but you can rent it for three minutes!"',
  '"Life’s a little bit messy. We all make mistakes. No matter what type of animal you are, change starts with you."',
  '"I can do this all day!"',
  "\"My dad used to say, 'If you live an ordinary life, all you'll have are ordinary stories. You have to live a life of adventure.'\"",
  '"Start With Where You\'re From"',
  '"PWinston... tell them... Tell them all... Whoever comes, whoever it is... I\'ll kill them. I\'ll kill them all."',
  '"Do you know what a Cinnabon is? It\'s bread! And frosting! And cinnamon! They heat it up! Really hot!"',
  '"Life is a big trap, made up of little traps... If you listen hard... sometimes you could hear them snap shut."',
  "\"Don't do anything I would do, and definitely don't do anything I wouldn't do...\"",
  '"There’s no hiding from this, son."',
  '"When all seems lost, a few brave souls can save everything we\'ve ever known."',
  '"I promise you ... No matter where we will be in this world ... I promise we will meet again."',
  '"Unfortunately, we’re all human. Except me, of course."',
  '"Break hearts, not promises."',
  '"Every time we get a chance to get ahead they move the finish line, every time."',
  '"When we lose our principles, we invite chaos."',
  '"People walk around, act like they know what hate means. Nah, no one does, until you hate yourself. I mean truly hate yourself. That’s power."',
  '"We Shall Never Surrender."',
  '"I have burrowed underneath your brain. I am nested there. I am the scream in your mind. You will cooperate."',
  '"Treasure the experience. Dreams fade away after you wake up"',
  '"Leave One Wolf Alive and the Sheep are Never Safe"',
  '"Love\'s the most powerful emotion and that makes it the most dangerous"',
  '"You’re so dark! Are you sure you’re not from the DC universe? I love dubstep!"',
  '"If you want to change things in a big way, then you gotta make some big changes."',
  '"Just because something works doesn’t mean it can’t be improved."',
  '"There is no such thing as magic, just illusion. Things only change when we change them. But you have to do it skillfully, in secret. Then it seems like magic."',
  '"The darkest nights produce the brightest stars."',
  '"That’s one small step for man, one giant leap for mankind."',
  '"Is this your king?"',
  '"That person who helps others simply because it should or must be done, and because it is the right thing to do, is indeed without a doubt, a real superhero."',
  '"If we didn’t do what we loved, we wouldn’t exist."',
  '"Sometimes we think we have to do it all on our own. But we don’t."',
  '"I just wanted to take another look at you."',
  '"The hardest choices require the strongest wills"',
  '"What’s done is done, when we say it’s done."',
  '"Change is like death. You don’t know what it looks like until you’re standing at the gates."',
  "\"Being a hero doesn't mean you are invincible. It just means you're brave enough to stand up, and do what's needed.\"",
  '"Sometimes, when you\'re feeling helpless, the secret is to help someone else. Get out of your own head. Trust me. The next time someone asks for help, say yes."',
  '"Yeah. Well, you’re right. I thought it was more important to be somebody out there than the damn failure I was here at my own home. Anyway, for what it’s worth, I’m here now."',
  '"Whatever it takes!"',
  '"That does put a smile on my face."',
  '"For I am a Sinner in the hands of an angry God, Bloody Mary, Full of Vodka, Blessed are you among cocktails, pray for me now, at the hour of my death, which I hope is soon. Amen"',
  '"Being genius is not enough, it takes courage to change people\'s hearts."',
  '"Elsa, the past is not what it seems. You must find the truth."',
  '"I remember the story of an evil witch, at the princess she cursed to sleep forever. The story became legend. But this is no fairy tale."',
  '"I can do this all day"',
  '"I love you 3000."',
  '"I laugh in the face of danger"',
  '"Being brave doesn’t mean you go looking for trouble."',
  '"Lord knows, I’ve held onto way too much hate in my life. But all we have is now. All we have is now."',
  '"All I have are negative thoughts."',
  '"Nothing is funnier than unhappiness."',
  '"Is it just me, or is it getting crazier out there?"',
  '" If you want to get crazy. We can get crazy."',
  '"A new chapter of my life has begun. Already, I can feel the weight of this crown I wear."',
  '"You all love twisting the knife into one another."',
  '"Things are very uncomfortable between us, but we’re stuck in a house together."',
  '"Pearl Harbor is the greatest intelligence failure in American history."',
  '"There’s nothing you can’t do if you try."',
  '"I just want to escape. Dad always wanted me to travel the world. Someday."',
  '"They have all the money, all the firepower, and they’ll use it. I know, I was one of them."',
  '"I think the best thing we can do is to let people know that each one of them is precious."',
  '"Well, I’ve got no leashes, or fences. With me, every day could be an adventure."',
  '"You\'re really lucky, you know that? You didn\'t have to wait your whole life to do something special."',
  '"Even if we do ignore the previous data, Broly\'s latent abilities are quite remarkable."',
  '"My mother always tells me to smile and put on a happy face. She told me I had a purpose to bring laughter and joy to the world."',
  '"How truly magnificent! I think this battle is about to come to a rousing finale!"',
  '"Today the impossible becomes the possible. "',
  '"There is no punchline."',
  '"Is it just me, or is it getting crazier out there?’"',
  '"That\'s MotherF****** street poetic justice."',
  '"Maybe it\'s because I\'m constantly fighting, destro…d to be a lower-class warrior... like my Kakarot."',
  '"These barbarians pretend to be submissive, but the…a sleeping beast down, before it can be awakened."',
  '"Time means nothing. Jeremy Bearimy, baby. We’ll just get through this. And then you and I can chill out in the dot of the I forever."',
  '"The worst part of having a mental illness is people expect you to behave as if you don\'t"',
  '"You give me your loyalty, and I’ll guarantee that each and every one of you will have a chance to be a warrior, to actually be a part of history."',
  '"What do you want most in the world?"',
  '"I do what I do because of my dad. He was a hero. He gave his life for the pursuit of knowledge."',
  '"You\'ve got a lot to learn. Here on Earth, we like …have to listen to what the others tell you to do."',
  '"Following\'s not really my style."',
  '"I have nothing to prove to you"',
  '"Dude, you are on fire."',
  '"This is me. This is how I win."',
  '"Why have average when you can have extraordinary?"',
  '"You are my lighting rod."',
  '"I used to think that my life was a tragedy. But now I realize, it’s a comedy."',
  '"I use the words you taught me. If they don\'t mean anything any more, teach me others. Or let me be silent."',
  '"I used to use this little gun when I was a prostitude."',
  '"If you want to get crazy. We can get crazy."',
  '"If you can only do one thing, hone it to perfection. Hone it to the utmost limit!"',
  '"You get what you f***ing deserve !!"',
  '"You don\'t listen, do you?"',
  '"Never let your wings be stolen for you"',
  '"Guns, lots of guns."',
  '"I was so sure my strength was getting close to it\'…on this planet... Then who would I train against."',
  '"No amount of money ever bought a second of time."',
  '"The end is in the beginning and yet you go on."',
  '"This meeting of The Losers Club has officially begun."',
  '" Spider-Pig, Spider-Pig. Does whatever a Spider-Pig does. Can he swing from a web? No he can\'t, he\'s a pig. Look out! He is a Spider-Pig!"',
  '"Let’s do this."',
  '"It looks as though he\'s managed to transform someh… his human form, retaining his speed and agility."',
  '"I just hope my death makes more cents than my life."',
  '"I am Iron Man."',
  '"I didn\'t know if you were lost. Stick with me. I\'ll keep you safe."',
  '"This guy\'s awesome! He\'s holding his own while still in his base form!"',
  '"Murder is murder, it don’t matter who you are."',
  '"That was the best acting i\'ve ever seen in my whole life."',
];
